language: bash

install:
  - docker build -t farshidtz/zmq4-arm .

before_script:
  - git clone https://github.com/pebbe/zmq4.git src/github.com/pebbe/zmq4

script:
  - docker run --rm -v $(pwd):/home farshidtz/zmq4-arm -o bin/wuserver src/github.com/pebbe/zmq4/examples/wuserver.go

before_deploy:
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin

deploy:
  - provider: script
    script: docker push farshidtz/zmq4-arm
    on:
      branch: master
