language: bash

before_script:
  - docker build -t farshidtz/zmq4-arm .

script:
  - wget https://raw.githubusercontent.com/pebbe/zmq4/master/examples/wuserver.go
  - go get github.com/pebbe/zmq4
  - docker run --rm -v $(pwd):/home farshidtz/zmq4-arm -o bin/wuserver wuserver.go

before_deploy:
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin

deploy:
  - provider: script
    script: docker push farshidtz/zmq4-arm
    on:
      branch: master
