language: bash

services:
  - docker

before_script:
  - wget https://raw.githubusercontent.com/pebbe/zmq4/master/examples/wuserver.go

script:
  - docker run --rm -v $(pwd):/home farshidtz/zmq4-arm -o bin/wuserver wuserver.go